# Generated by Django 5.2.5 on 2025-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.ImageField(upload_to='images')),
                ('upload_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
