# Generated by Django 5.2.5 on 2025-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='upload_At',
            new_name='uploaded_At',
        ),
    ]
